"""
[Phase Three: Personas]

Persona objects represent characters. I'm going with the odd names for a reason, 
which is just for fun and given what this project is about I figured it would fit 
thematically. Persona subclasses Actor, meaning it carries 3 sub-notes (worldline, library, sketchpad)
to represent their short-term, long-term, and working memories, respectively.

Personas also have methods that take a description of what is happening around them,
and return a description of what they are going to think/do/say, 
plus an initiative value to determine action order.

Two Persona types are available. 
One that uses a WorldlineAgent to have an LLM determine its actions,
and one that connects to a human player over a network connection (not yet implemented, that's for phase 5).
"""

import typing
import dspy

from worldline.uid import UID
from worldline.data import Context, Note
from worldline.agent import WorldlineAgent, Actor

# initiative scores, 0 through 10 inclusive, 0 means no action
Initiative = int

class Action(typing.NamedTuple):
    """Represents a planned action generated by a Persona.

    Attributes:
        initiative (int): A score from 0 to 10 indicating action speed. 
            0 indicates no action.
        action (typing.Optional[str]): A first-person description of the intended 
            action. Ignored or None if initiative is 0.
    """
    initiative: Initiative
    action: typing.Optional[str] = None

class Persona(Actor):
    """Base class for character entities acting within the Fate Engine.

    Personas process scene descriptions and generate optimistic actions based 
    on their internal memory, timeline, and current thoughts.

    Attributes:
        _sys_scene_notes (typing.ClassVar[str]): Format string used by the 
            Fate Engine to describe scenes to this Persona.
    """

    # for Fate Engine
    _sys_scene_notes: typing.ClassVar[str] = "Describe what {name} sees or perceives."

    def turn(self, scene: str) -> Action:
        """Processes a scene observation and declares an intended action.

        Args:
            scene (str): The narrative description of what the Persona observes.

        Returns:
            Action: A tuple containing the Persona's initiative roll and 
                their intended action prose.
        """
        return Action(0, None)

    @property
    def sys_scene_notes(self) -> str:
        """Returns the formatted system scene notes specific to this Persona.

        Returns:
            str: The formatted instruction string for the Fate Engine.
        """
        return self._sys_scene_notes.format(name=self.name)


class AgentPersona(Persona):
    """An LLM-driven Persona that uses DSPy to autonomously generate actions.

    Attributes:
        _sys_scene_notes (typing.ClassVar[str]): Specialized LLM formatting instructions.
        _agent (typing.Optional[WorldlineAgent]): Cached singleton of the ReAct agent.
    """

    AGENT_SIGNATURE: typing.ClassVar[type[dspy.Signature]] = dspy.make_signature(
        signature={
            "name": (
                str,
                dspy.InputField(desc="Your name."),
            ),
            "scene": (
                str, 
                dspy.InputField(desc="A description of what you perceive."),
            ),
            "initiative": (
                int, 
                dspy.OutputField(desc="An integer, 0 through 10 inclusive, for how quickly you can or will act. Higher is faster. 0 indicates that you do not want to do anything at this moment.", ge=0, le=10),
            ),
            "action": (
                str, 
                dspy.OutputField(desc="What you do, if no one else does something first. Write in first-person perspective. Ignored if initative = 0 (put 'N/A' or similar)."),
            ),
        },
        instructions="""You are a character in a story. You are to record what you see and what you think, and come up with a plan for what you will do next.
You are to return an integer representing how quickly you will act, as well as a first-person narrated description of what you will do if not interrupted.
Your Timeline stores your short-term memory, along with what you are perceiving and your current thought processes, record these there. 
Your Memory is where your longer-term memories are stored, if you get useful information to keep around, store it there.
Your Moment is where you should write what you are thinking about this exact moment.
IMPORTANT: Someone else may act before you are able to, so do not record in your timeline, memory, or sketchpad that you have done what you plan to do, only that you plan to do it.""",
    )

    _sys_scene_notes: typing.ClassVar[str] = "Describe what {name} sees or perceives. Provide plenty of direct detail, avoid metaphors and such. Ensure to only include what {name} actually can perceive."

    _agent: typing.Optional[WorldlineAgent] = None

    @property
    def agent(self) -> WorldlineAgent:
        """Lazily instantiates and returns the underlying WorldlineAgent.

        Constructs the DSPy signature and ReAct module only upon first access,
        ensuring safe instantiation when loading from save files.

        Returns:
            WorldlineAgent: The configured DSPy ReAct agent for this Persona.
        """
        if self._agent is None:
            self._agent = WorldlineAgent(
                self.ctx,
                self.AGENT_SIGNATURE,
                [self.timeline, self.memory, self.moment],
                self.tools,
            )

        return self._agent

    def turn(self, scene: str) -> Action:
        """Executes the DSPy agent to process the scene and decide on an action.

        Args:
            scene (str): The narrative description of what the Persona observes.

        Returns:
            Action: The resulting initiative and action prose. Returns an initiative
                of 0 if the agent decides not to act.
        """
        try:
            result = self.agent(name=self.name, scene=scene)
            if result.initiative:
                return Action(result.initiative, result.action)
            return Action(0, None)
        except Exception as e:
            return Action(0, None)

# TODO: write this later
# maybe move it to another class?
class UserPersona(Persona):
    pass